### ISSUE TITLE
Sort_ver2 Task List

### ISSUE THREAD

**Issue by 2-phones** [Sort-Project/sort_ver2#5]
## Task List

전체적으로 리팩토링 해야될일 리스트 입니다.

## Client

- [ ] 카테고리 버튼 클릭시 해당 카테고리 상품 렌더링

- [ ] 로딩시 스켈레톤 UI

- [ ] 타입스크립트 리팩토링

- [ ] 찜기능, 조회, 생성 로직 구현

- [ ] 구매 확정 기능 추가

## Server

- [ ] 전체 ,판매중 ,판매완료 로직구현

- [ ] 검색후 태그 삭제시 다시 전체 상품 렌더링

- [ ] 채팅 서버, DB 구현

-  [ ] 찜 기능, DB 구현

-  [ ] Jwt 로그인 기능

-  [ ] 카테고리 버튼 클릭시 해당 카테고리 상품 렌더링

-  [ ] 상품등록시 사진 업로드 기능

- [ ] 구매 , 판매 , 찜 각각 DB 테이블, 클라이언트에서 조회 가능하도록 로직구현

- [ ] 구매 확정후 거래후기
